version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: apache
    ports:
      - "8183:80"
    volumes:
      - ./web:/var/www/html