version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: ./Dockerfile_Web
    container_name: apache_webvmrecio
    ports:
      - "8183:80"
    volumes:
      - ./web:/var/www/html